apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
  labels:
    app: devopsapp
spec:
  template:
    metadata:
      name: devopsapp-pod
      labels:
        app: devopsapp
        type: back-end
    spec:
      containers:
        - name: i-ankitkawtia-main
          image: ankitkawtia/i-ankitkawtia-main:latest
          #envFrom:
           # - secretRef:
            #    name: secretInfo
  replicas: 4
  selector:
    matchLabels:
      type: back-end
      app: devopsapp

---
apiVersion: v1
kind: Service
metadata:
 name: devopsapp-lb-service
spec:
 type: LoadBalancer
 ports:
 - targetPort: 80
   port: 80
   nodePort: 30081
 selector:
  app: devopsapp
  type: back-end
