apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment-develop
  namespace: kubernetes-cluster-ankitkawtia
  labels:
    app: devopsappdevelop
spec:
  template:
    metadata:
      name: devopsapp-develop
      labels:
        app: devopsappdevelop
    spec:
      containers:
        - name: i-ankitkawtia-develop
          image: ankitkawtia/i-ankitkawtia-develop:latest
          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets
  replicas: 4
  selector:
    matchLabels:
      app: devopsappdevelop

---
apiVersion: v1
kind: Service
metadata:
 name: devopsapp-lb-service-develop
 namespace: kubernetes-cluster-ankitkawtia
 labels:
   app: devopsapp-lb-develop
spec:
 type: LoadBalancer
 ports:
 - targetPort: 8082
   port: 80
   nodePort: 30081
 selector:
  app: devopsappdevelop
