apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment-master
  namespace: kubernetes-cluster-ankitkawtia
  labels:
    app: devopsappmaster
spec:
  template:
    metadata:
      name: devopsapp-master
      labels:
        app: devopsappmaster
    spec:
      containers:
        - name: i-ankitkawtia-master
          image: ankitkawtia/i-ankitkawtia-master:latest
          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets
  replicas: 4
  selector:
    matchLabels:
      app: devopsappmaster

---
apiVersion: v1
kind: Service
metadata:
 name: devopsapp-lb-service-master
 namespace: kubernetes-cluster-ankitkawtia
 labels:
   app: devopsapp-lb-master
spec:
 type: LoadBalancer
 ports:
 - targetPort: 8083
   port: 80
   nodePort: 30083
 selector:
  app: devopsappmaster
