apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
  labels:
    app: devopsapp
spec:
  template:
    metadata:
      name: devopsapp-pod
      labels:
        app: devopsapp
    spec:
      containers:
        - name: i-ankitkawtia-main
          image: ankitkawtia/i-ankitkawtia-main:latest
          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secrets
  replicas: 4
  selector:
    matchLabels:
      app: devopsapp

---
apiVersion: v1
kind: Service
metadata:
 name: devopsapp-lb-service
 labels:
   app: devopsapp-lb
spec:
 type: LoadBalancer
 ports:
 - targetPort: 80
   port: 80
   nodePort: 30081
 selector:
  app: devopsapp
